### ISSUE TITLE
InTune policy conflict within hardening guide for windows 10 and later settings catalog

### ISSUE THREAD

**Issue by CryptikCrisis** [microsoft/Intune-ACSC-Windows-Hardening-Guidelines#4]
In the ACSC hardened template for Windows 10 and later. The setting Browser -> Allow Password Manager (User/Computer) causes a conflict with Microsoft Edge -> Password manager and protection -> Enable saving passwords to the password manager (User/Computer)

The Browser settings are Policy-CSP items that only apply to Microsoft Edge 45 and earlier. The Microsoft Edge policy itself is the correct policy that applies to Edge 46 and later

To resolve this, we have to align all ALL 4 settings to resolve the conflict or remove the Browser settings from the catalogue settings.

**Comment by midineenMSFT** [comment]
Thank you for opening this issue and providing this feedback. I will implement the changes to resolve the conflicts, as well as update the relevant Edge settings in the coming weeks.

**Comment by midineenMSFT** [comment]
@CryptikCrisis I've updated the 'Windows Security Baseline (for use with ACSC Windows Hardening Guidelines)' policy to remove the conflict with Password Manager. I've opted to keep this setting in the 'Intune ACSC Windows Hardening Guidelines' in case someone has chosen not to deploy the Edge Security Baselines alongside this policy (in which case, the conflict will have to be resolved manually). 
Please let me know if you had any additional input or if this does not resolve the issue.
