### ISSUE TITLE
New version of Windows Security Baseline is  now available- update here?

### ISSUE THREAD

**Issue by directorcia** [microsoft/Intune-ACSC-Windows-Hardening-Guidelines#9]
A new Windows Security Baseline policy is now available. It is significantly different from the previous one and I also believe needs to be deployed in a different manner to a different endpoint? Is there any plans to update what's here to accommodate this new Windows Baseline Security policy?

**Comment by midineenMSFT** [comment]
Hi @directorcia, please see this branch which has the latest updates to incorporate the 23H2 Windows Security Baselines along with numerous improvements and conflict resolutions. This branch will be promoted to main after additional testing in the next few weeks.
[https://github.com/microsoft/Intune-ACSC-Windows-Hardening-Guidelines/tree/23H2-Windows-Security-Baseline](https://github.com/microsoft/Intune-ACSC-Windows-Hardening-Guidelines/tree/23H2-Windows-Security-Baseline)

**Comment by directorcia** [comment]
Thanks for the update and speed of moving this change forward. Can't wait till it hits production.
